import os
from dotenv import load_dotenv

load_dotenv()

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT"))
DEFAULT_USER_DOWNLOAD_LIMIT = 1
PREMIUM_USER_DOWNLOAD_LIMIT = 3
MAX_CONCURRENT_DOWNLOADS = 2
MAX_RETRIES_FOR_DOWNLOAD = 1