"""create movie_mirrors table

Revision ID: a9f460226ae5
Revises: 
Create Date: 2025-04-23 16:56:15.663728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f460226ae5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_mirrors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(), nullable=True),
    sa.Column('mirror_url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('geo_priority', sa.String(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_mirrors_id'), 'movie_mirrors', ['id'], unique=False)
    op.create_index(op.f('ix_movie_mirrors_movie_id'), 'movie_mirrors', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_mirrors_movie_id'), table_name='movie_mirrors')
    op.drop_index(op.f('ix_movie_mirrors_id'), table_name='movie_mirrors')
    op.drop_table('movie_mirrors')
    # ### end Alembic commands ###
